
import type { Metadata } from "next";
import "./globals.css";
import PageTransition from "./PageTransition";
import SideNav from "./ui/navBar";
import Footer from "./ui/footer";
import { ContactInfo } from "./ui/contactInfo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:'favicon.ico'
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <head>
        <link
            href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap"
            rel="stylesheet"
          />
      </head>
      <body
        className={`antialiased`}
      >
        <SideNav/>
        
        {/* 使用 PageTransition 包裹页面内容 */}
        <PageTransition>{children}</PageTransition>
        <ContactInfo/>
        <Footer/>
      </body>
    </html>
  );
}
